Chat/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/",include("main.urls")),
    path('accounts/', include('allauth.urls')),
    path("auth/",include("accapp.urls")),
]

accapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name="accapp"

urlpatterns = [
        path("signup/",views.signup,name="signup"),
        path("",auth_views.LoginView.as_view(template_name="account/login.html"),name="login"),
        path("logout/",auth_views.LogoutView.as_view(),name="logout"),
        ]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
        path("",views.index,name="index"),
        path("chatroom/<slug:slug>/",views.chatroom,name="chatroom"),
        ]

accapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

class User(AbstractUser):
    id = models.UUIDField(
            primary_key=True,
            default=uuid.uuid4,
            editable=False,)

    username = models.CharField(max_length=200,unique=True)
    email = models.EmailField()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

class ChatRoom(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name="sender")
    message = models.TextField()
    receiver = models.ForeignKey(ChatRoom,on_delete=models.CASCADE,related_name="reveiver")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ("date",)

accapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegistrationForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        username = forms.CharField(
                label="",
                help_text="",
                widget = forms.TextInput(attrs={
                    "name":"username",
                    "type":"text",
                    "placeholder":"Username",
                    "id":"username",
                    "class":"input username",
                    }
                )
            )

        email = forms.EmailField(
                label="",
                widget = forms.TextInput(attrs={
                    "name":"email",
                    "type":"email",
                    "placeholder":"Email",
                    "id":"email",
                    "class":"input email"
                    }
                )
            )

        password1 = forms.CharField(
                label="",
                help_text="",
                widget=forms.PasswordInput(attrs={
                    "name":"password1",
                    "id":"password",
                    "placeholder":"Password",
                    "type":"password",
                    "class":"input password",
                    }
                )
                )

        password2 = forms.CharField(
                label="",
                help_text="",
                widget=forms.PasswordInput(attrs={
                    "name":"password2",
                    "id":"password",
                    "placeholder":"Confirm Password",
                    "type":"password",
                    "class":"input password",
                    }
                )
            )

        class Meta:
            model = User
            fields = ["username","email"]

accapp/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from .forms import UserRegistrationForm

User = get_user_model()

def signup(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            form.save()
        else:
            print("error")

    else:
        form = UserRegistrationForm()

    return render(request,"account/signup.html",{"form":form})

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
from .models import ChatRoom,Message
from django.contrib.auth.decorators import login_required


@login_required
def index(request:HttpRequest):

    chatrooms = ChatRoom.objects.all()
    context = {"chatrooms":chatrooms}
    return render(request,"main/index.html",context)


@login_required
def chatroom(request:HttpRequest,slug):
    chatroom = ChatRoom.objects.get(slug=slug)
    messages = Message.objects.filter(receiver=chatroom)

    context = {"chatroom":chatroom,"messages":messages}
    return render(request,"main/chatroom.html",context)

main/templates/main/chatroom.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>ChatRoom | ChatApp</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    </head>
    <body>
        <nav
            class="d-flex justify-content-between align-content-center p-2 nav-bar"
        >
            <div>
                <h2 class="text-success fs-3">Django Chat</h2>
            </div>
            <div class="d-flex">
               <!-- <a href="{% url 'account:logout' %}"
                    ><button class="btn bg-warning">logout</button></a
                    >-->
            </div>
        </nav>

        <div class="row">
            <h2 class="text-start p-3 my-3 mx-3 text-warning">
                {{ chatroom.name }}
            </h2>
        </div>
        <div class="container">
            <div class="row chatbox">
                {% for message in messages %}
                <div class="messages bg-white rounded mx-2 my-2">
                    <h5 class="text-start p-2 text-warning">
                        {{ message.sender }}
                    </h5>
                    <p class="text-dark m-2">{{ message.message }}</p>
                    <p class="float-end">{{ message.date }}</p>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="container">
            <div class="row d-flex justify-content-between">
              <form id="messageform">
                
              
                <div class="col d-flex mb-5">
                    <input
                        type="text" id="chatmessage"
                        placeholder="Write message.."
                        class="form-control mx-2"
                    />
                    <button class="btn btn-primary">send</button>
                </div>
                </form>
            </div>
        </div>
        {{ chatroom.slug|json_script:"room-name"}}
        {{ request.user.username|json_script:"username"}}
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"
        ></script>
        <script src="{% static 'js/index.js' %}"></script>
    </body>
</html>

main/templates/main/index.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Chat Rooms | ChatApp</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    </head>
    <body>
        <nav
            class="d-flex justify-content-between align-content-center p-2 nav-bar"
        >
            <div>
                <h2 class="text-success fs-3">Django Chat</h2>
            </div>
            <div class="d-flex">
               <!-- <a href="{% url 'account:logout' %}"
                    ><button class="btn bg-warning">logout</button></a
                    >-->
            </div>
        </nav>

        <h4 class="text-center text-white my-4">Chat Rooms</h4>
        <div class="row my-2 mx-2">
            {% for chatroom in chatrooms %}
            <div class="col-12 col-sm-4 g-3 g-sm-5">
              <a href="{% url 'main:chatroom' chatroom.slug %}" style="text-decoration:none; color:orange;">
                <div class="room bg-white rounded">
                    <h4 class="text-start p-2">{{ chatroom.name}} chat </h4>
                </div>
              </a>
            </div>
            {% endfor %}
        </div>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"
        ></script>
    </body>
</html>